### ISSUE TITLE
Branch deveploment 

### ISSUE THREAD

**Issue by ambarja** [r-earthengine/r-earthengine.github.io#2]
@csaybar he creado una nueva rama de desarrollo, ahora me aparece los tag y las categorías , pero no el código, quizás siempre debo de estar poniendo stop al server y borando el caché, no estoy muy seguro.
Sin embargo ayer lo hice modo de prueba hoy realmente estaré enfocado en seguir los demás examples.
saludos

**Comment by csaybar** [comment]
hola has cambios en la rama master no hay problema! ...  ademas el GH solo se activa cuando hay cambios en el master!

**Comment by csaybar** [comment]
![image](https://user-images.githubusercontent.com/16768318/103363117-a6ef3880-4aba-11eb-8d8a-78ec4464446a.png)
